---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: Você pode configurar um nó único que não é HA em configurações pequenas ou médias. 
---
= Implantar as ferramentas do ONTAP para o VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode implantar as ferramentas do ONTAP para o VMware vSphere em duas configurações:

* Configuração de nó único não HA
* Configuração HA


[role="tabbed-block"]
====
.Configuração de nó único não HA
--
Você pode implantar uma configuração de nó único que não seja HA em uma configuração pequena ou média.

* A pequena configuração não-HA contém 8 CPUs e 16 GB de RAM.
* A configuração média não-HA contém 12 CPUs e 24 GB de RAM.


*Antes de começar*

Certifique-se de que a rota de rede está presente. A rede de dados de storage deve estar acessível a partir da rede de gerenciamento de VM. Por exemplo, faça login no ONTAP > execute o comando _network route create -vserver <SVM> -destination 0,0.0.0/0 -gateway <gateway_ip>_

*Passos*

. Faça o download do `.zip` arquivo que contém binários (_.ova_) e certificados assinados para ferramentas do ONTAP para VMware vSphere no https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^] .
. Faça login no servidor vSphere.
. Navegue até o pool de recursos que você criou, para o cluster ou para o host onde deseja implantar o OVA.
. Clique com o botão direito do rato no local pretendido e selecione *Deploy OVF template...*.
+

NOTE: Não implante ferramentas do ONTAP para a máquina virtual VMware vSphere em um datastore vVols que ele gerencia.

. Selecione o arquivo OVA através da URL do arquivo _.ova_ ou navegue até a pasta onde o arquivo _.ova_ é salvo e clique em *Next*.
. Selecione um recurso de computador e clique em *Next*.
. Revise os detalhes do modelo e clique em *Next*.
. Leia e aceite o contrato de licença.
. Selecione a configuração de implantação e clique em *Next*.
+
As opções avançadas de implantação usam o Trident como um provisionador de storage dinâmico para o ONTAP para criar volumes e a implantação fácil usa o storage local para criar volumes.

. Selecione o armazenamento para a configuração e os arquivos de disco e clique em *Next*.
. Selecione a rede de destino para cada rede de origem e clique em *Next*.
. No modelo *Personalizar*, insira os detalhes necessários e clique em *Avançar*
+
** Quando o escopo da SVM estiver ativado, você já deverá ter o suporte à SVM com endereço IP de gerenciamento.
** As informações fornecidas aqui são validadas para padrões adequados durante o processo de instalação. Em caso de discrepância, uma mensagem de erro é exibida no console da Web e você é solicitado a corrigir qualquer informação incorreta fornecida.
** Os nomes dos hosts devem consistir em letras maiúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) ou carateres especiais hífen (-). Se você quiser configurar a pilha dupla, especifique o nome do host mapeado para o endereço IPv6.
+

NOTE: O Pure IPv6 não é compatível. O modo misto é suportado com VLAN com endereços IPv6 e IPv4.



. Revise os detalhes na janela *Pronto para concluir*, selecione *concluir*.
+
À medida que a tarefa de implantação é criada, o progresso é mostrado na barra de tarefas do vSphere.

. Ligue a VM após a conclusão da tarefa.


--
.Configuração HA
--
Você pode configurar três nós de HA em configurações pequenas, médias ou grandes. A implantação DE HA usa o Trident para armazenar os dados dos serviços.

* Três nós de HA pequenos contêm 8 CPUs e 16 GB de RAM por nó.
* Três nós de HA média contêm 12 CPUs e 24 GB de RAM por nó.
* Os três nós de HA grandes contêm 16 CPUs e 32 GB de RAM por nó.


*Antes de começar*

Esta tarefa fornece instruções sobre como instalar três nós de HA em configurações pequenas, médias ou altas.

A criação da biblioteca de conteúdo é uma etapa de pré-requisito obrigatória para a implantação da configuração de três nós HA. Uma biblioteca de conteúdo no VMware é um objeto de contentor que armazena modelos de VM, modelos vApp e outros tipos de arquivos. A implantação com biblioteca de conteúdo oferece uma experiência perfeita, pois não depende da conetividade de rede.


NOTE: Você deve armazenar a biblioteca de conteúdo em um datastore compartilhado, de modo que todos os hosts em um cluster possam acessá-la. Você precisa criar uma biblioteca de conteúdo para armazenar o OVA antes de implantar o OVA na configuração HA.


NOTE: O modelo de biblioteca de conteúdo, uma vez carregado, não deve ser excluído após a implantação, pois ele será usado durante as reinicializações.

Crie a biblioteca de conteúdo usando as seguintes etapas:

. Faça o download do `.zip` arquivo que contém binários (_.ova_) e certificados assinados para ferramentas do ONTAP para VMware vSphere no https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^] .
. Faça login no cliente vSphere usando `\https://vcenterip/ui`
. Selecione as elipses horizontais ao lado do cliente vSphere e selecione *Content Library*.
. Selecione *criar* à direita da página.
. Forneça um nome para a biblioteca e crie a biblioteca de conteúdo.
. Navegue até a biblioteca de conteúdo que você criou.
. Selecione *ações* à direita da página e selecione *Importar item* e importe o arquivo OVA.



NOTE: Para obter mais informações, https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Criando e usando a Biblioteca de conteúdo"] consulte o blog.

Certifique-se de ter importado seu OVA para sua biblioteca de conteúdo. Mantenha o nome da biblioteca de conteúdo e o nome do item da biblioteca que você deu ao ITEM OVA à mão.


NOTE: Antes de prosseguir com a implantação, defina o DRS (Distributed Resource Scheduler) do cluster no inventário como 'Conservador' durante a instalação de ferramentas do ONTAP. Isso garante que as VMs não migrem durante a instalação.

*Passos*

. Faça o download do `.zip` arquivo que contém binários (_.ova_) e certificados assinados para ferramentas do ONTAP para VMware vSphere no https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^] .
. Faça login no servidor vSphere.
. Navegue até o pool de recursos que você criou, para o cluster ou para o host onde deseja implantar o OVA.
. Clique com o botão direito do rato no local pretendido e selecione *Deploy OVF template...*.
+

NOTE: Não implante ferramentas do ONTAP para a máquina virtual VMware vSphere em um datastore vVols que ele gerencia.

. Selecione o arquivo OVA através da URL do arquivo _.ova_ ou navegue até a pasta onde o arquivo _.ova_ é salvo e clique em *Next*.
. Para implantar as ferramentas do ONTAP para VMware vSphere a partir da biblioteca de conteúdo:
+
.. Vá para sua biblioteca de conteúdo e clique no item da biblioteca que você deseja implantar.
.. Clique em *ações* > *Nova VM a partir deste modelo*


. Selecione um recurso de computador e clique em *Next*.
. Revise os detalhes do modelo e clique em *Next*.
. Leia e aceite o contrato de licença e clique em *Next*.
. Selecione a configuração de implantação e clique em *Next*.
. Selecione o armazenamento para a configuração e os arquivos de disco e clique em *Next*.
. Selecione a rede de destino para cada rede de origem e clique em *Next*.
. Na janela *Personalizar modelo*, preencha os campos obrigatórios e clique em *seguinte*.
+
** No modo de implantação HA, não renomeie os nomes da VM após a implantação.
** Quando o escopo da SVM estiver ativado, você já deverá ter o suporte à SVM com endereço IP de gerenciamento.
** As informações fornecidas aqui são validadas para padrões adequados durante o processo de instalação. Em caso de discrepância, uma mensagem de erro é exibida no console da Web e você é solicitado a corrigir qualquer informação incorreta fornecida.
** Os nomes dos hosts devem consistir em letras maiúsculas (A-Z), letras minúsculas (a-z), dígitos (0-9) ou carateres especiais hífen (-). Se você quiser configurar a pilha dupla, especifique o nome do host mapeado para o endereço IPv6.
+

NOTE: O Pure IPv6 não é compatível. O modo misto é suportado com VLAN com endereços IPv6 e IPv4.



. Revise os detalhes na janela *Pronto para concluir*, selecione *concluir*.
+
À medida que a tarefa de implantação é criada, o progresso é mostrado na barra de tarefas do vSphere.

. Ligue a VM após a conclusão da tarefa.


--
====
Você pode acompanhar o andamento da instalação no console da Web da VM.

Em caso de discrepâncias nos valores inseridos no formulário OVF, uma caixa de diálogo solicitará que você tome medidas corretivas. Faça as alterações necessárias dentro da caixa de diálogo, utilizando o botão Tab para navegar e selecione "OK". Você tem três tentativas para corrigir quaisquer problemas. Se os problemas persistirem após três tentativas, o processo de instalação cessará e é recomendável tentar novamente a instalação em uma nova VM.
