---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.' 
---
= Configure o SRA para ambientes altamente dimensionados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve configurar os intervalos de tempo de armazenamento de acordo com as configurações recomendadas para Storage Replication Adapter (SRA) para ter um desempenho ideal em ambientes altamente dimensionados.



== Definições do fornecedor de armazenamento

Você deve definir os seguintes valores de tempo limite no VMware Live Site Recovery para ambiente dimensionado:

|===


| * Configurações avançadas* | *Valores de tempo limite* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Aumente o valor da definição de 900 segundos para 12000 segundos.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Definir um valor alto (por exemplo: 99999)

|===
Você também deve ativar a `StorageProvider.autoResignatureMode` opção.

Consulte a documentação da VMware para obter mais informações sobre como modificar as configurações do provedor de armazenamento.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["Documentação do VMware vSphere: Altere as configurações do provedor de armazenamento"]



== Definições de armazenamento

Quando você atinge um tempo limite, aumente os valores de `storage.commandTimeout` e `storage.maxConcurrentCommandCnt` para um valor mais alto.


NOTE: O intervalo de tempo limite especificado é o valor máximo. Não é necessário esperar que o tempo limite máximo seja atingido. A maioria dos comandos termina dentro do intervalo de tempo limite máximo definido.

Consulte a documentação da VMware sobre como modificar as configurações do provedor de SAN para obter mais informações.

https://docs.vmware.com/en/VMware-Live-Site-Recovery/9.0/vmware-live-site-recovery/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html["Documentação do VMware Site Recovery Manager: Altere as configurações de armazenamento"]
