---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere oferecem a opção de habilitar o recurso SRA para configurar a recuperação de desastres. 
---
= Ative o SRA para proteger datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para VMware vSphere oferecem a opção de habilitar o recurso SRA para configurar a recuperação de desastres.

*O que você vai precisar*

* Você deve ter configurado a instância do vCenter Server e configurado o host ESXi.
* Você deve ter implantado ferramentas do ONTAP.
* Você deve ter baixado o arquivo do adaptador SRA `.tar.gz` do https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Site de suporte da NetApp"^].


*Passos*

. Faça login na interface de gerenciamento do VMware Live Site Recovery Appliance usando o URL: `\https://:<srm_ip>:5480` E vá para adaptadores de replicação de armazenamento na interface de gerenciamento do VMware Live Site Recovery Appliance.
. Selecione *novo adaptador*.
. Carregue o instalador _.tar.gz_ para o plug-in SRA para o VMware Live Site Recovery.
. Volte a verificar os adaptadores para verificar se os detalhes estão atualizados na página adaptadores de replicação de armazenamento de recuperação de site do VMware Live.

