---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords:  
summary: Você pode optar por permitir alguns endereços de host ESXi específicos para operação de montagem de datastore. 
---
= Configurar o acesso à rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você tem vários endereços IP de host ESXi, todos os endereços IP descobertos do host são adicionados a uma política de exportação por padrão. Se você não quiser adicionar todos os endereços IP a uma política de exportação, forneça uma configuração para permitir endereços IP específicos em uma lista ou intervalo separados por vírgulas ou CIDR, ou uma combinação de todos os três para cada vCenter.

Você pode optar por permitir alguns endereços de host ESXi específicos para operação de montagem de datastore. Se a configuração não for fornecida, a política de exportação adicionará todos os endereços IP descobertos na etapa de pré-montagem. Se a configuração for fornecida, as ferramentas do ONTAP para VMware vSphere adicionarão apenas as que se enquadram nos endereços IP ou intervalo listados. Se nenhum dos endereços IP de um host pertencer aos endereços IP listados, a montagem nesse host falhará.

.Passos
. Faça login no cliente vSphere usando `\https://vcenterip/ui`
. Na página de atalhos, clique em *Ferramentas do NetApp ONTAP* na seção plug-ins.
. No painel esquerdo das ferramentas do ONTAP, navegue até *Configurações* > *Gerenciar acesso à rede* > *Editar*.
+
Use uma vírgula (,) para separar os endereços IP. Você pode especificar um endereço IP específico ou um intervalo de endereços IP ou endereços IPv6.

. Clique em *Salvar*.

