---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipathing do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp. 
---
= Configure as configurações multipath e timeout do servidor ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas do ONTAP para VMware vSphere verificam e definem as configurações de multipath do host ESXi e as configurações de tempo limite do HBA que funcionam melhor com os sistemas de armazenamento NetApp.

*Sobre esta tarefa*

Esse processo pode levar muito tempo, dependendo da configuração e da carga do sistema. O progresso da tarefa é exibido no painel tarefas recentes. À medida que as tarefas são concluídas, o ícone de alerta de status do host é substituído pelo ícone normal ou pelo ícone de reinicialização pendente.

*Passos*

. Na página inicial do VMware vSphere Web Client, clique em *hosts and clusters*.
. Clique com o botão direito do Mouse em um host e selecione *Ferramentas do NetApp ONTAP* > *Atualizar dados do host*.
. Na página de atalhos, clique em *Ferramentas do NetApp ONTAP* na seção plug-ins.
. Vá para o cartão de conformidade do host ESXi na visão geral (painel) das ferramentas do ONTAP para o plug-in do VMware vSphere.
. Selecione o link *Apply Recommended Settings* (aplicar configurações recomendadas).
. Na janela *Apply Recommended host settings* (aplicar configurações de host recomendadas), selecione os hosts que você deseja cumprir com as configurações de host recomendadas pelo NetApp e clique em *Next* (Avançar).
+

NOTE: Você pode expandir o host ESXi para ver os valores atuais.

. Na página de definições, selecione os valores recomendados, conforme necessário.
. No painel de resumo, verifique os valores e clique em *Finish*. Você pode acompanhar o progresso no painel de tarefas recentes.

