---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: Você pode definir tempos limite e outros valores nos hosts ESXi usando as ferramentas do ONTAP para VMware vSphere para garantir o melhor desempenho e o failover bem-sucedido. Os valores que as ferramentas do ONTAP para VMware vSphere definem são baseados no teste interno do NetApp. 
---
= Defina os valores do host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir tempos limite e outros valores nos hosts ESXi usando as ferramentas do ONTAP para VMware vSphere para garantir o melhor desempenho e o failover bem-sucedido. Os valores que as ferramentas do ONTAP para VMware vSphere definem são baseados no teste interno do NetApp.

Você pode definir os seguintes valores em um host ESXi:



== Definições do adaptador HBA/CNA

Define as definições de tempo limite de HBA recomendadas para sistemas de armazenamento NetApp.

* *Disk.QFullSampleSize*
+
Defina este valor como 32 para todas as configurações. Definir este valor ajuda a evitar erros de e/S.

* *Disk.QFullThreshold*
+
Defina este valor como 8 para todas as configurações. Definir este valor ajuda a evitar erros de e/S.

* *Tempos limite de Emulex FC HBA*
+
Use o valor padrão.

* *Tempos limite de tempo do QLogic FC HBA*
+
Use o valor padrão.





== Definições MPIO

Configurações MPIO definem caminhos preferidos para sistemas de armazenamento NetApp. As configurações do MPIO determinam quais dos caminhos disponíveis são otimizados (em vez de caminhos não otimizados que atravessam o cabo de interconexão) e definem o caminho preferido para um desses caminhos.

Em ambientes de alto desempenho, ou quando você estiver testando o desempenho com um único armazenamento de dados LUN, considere alterar a configuração de balanceamento de carga da política de seleção de caminho (PSP) de round-robin (VMW_PSP_RR) da configuração padrão de IOPS de 1000 para um valor de 1.



== Definições NFS

* *Net.TcpipHeapSize*
+
Defina este valor como 32.

* *Net.TcpipHeapMax*
+
Defina este valor como 1024MB.

* *NFS.MaxVolumes*
+
Defina este valor como 256.

* *NFS41.MaxVolumes*
+
Defina este valor como 256.

* *NFS.MaxQueueDepth*
+
Defina esse valor como 128 ou superior para evitar gargalos de enfileiramento.

* *NFS.HeartbeatMaxFailures*
+
Defina esse valor como 10 para todas as configurações NFS.

* *Frequência NFS.HeartbeatFrequency*
+
Defina esse valor como 12 para todas as configurações NFS.

* *NFS.HeartbeatTimeout*
+
Defina esse valor como 5 para todas as configurações NFS.


